version: '3.8'

services:

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge